version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  mysql-auth:
    image: mysql:8.0
    container_name: mysql-auth
    environment:
      MYSQL_DATABASE: authdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33061:3306"

  mysql-customer:
    image: mysql:8.0
    container_name: mysql-customer
    environment:
      MYSQL_DATABASE: customer
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33062:3306"

  mysql-accounts:
    image: mysql:8.0
    container_name: mysql-accounts
    environment:
      MYSQL_DATABASE: accounts
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33063:3306"

  mysql-transaction:
    image: mysql:8.0
    container_name: mysql-transaction
    environment:
      MYSQL_DATABASE: transaction
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33064:3306"

  audit-db:
    image: mysql:8.0
    container_name: audit-db
    environment:
      MYSQL_DATABASE: auditdb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
